CREATE TABLE IF NOT EXISTS notes
(
  id         INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title      VARCHAR(50)  NOT NULL,
  body       VARCHAR(255) NOT NULL,
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS books
(
  id         BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title      VARCHAR(50) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  -- TODO add user id
  INDEX title_idx (title)
);


CREATE TABLE IF NOT EXISTS book_records
(
  id         BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  book_id    INT         NOT NULL,
  read_date  DATE        NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  -- TODO add user id
  INDEX read_date_idx (read_date)
);
